import type { Metadata, Viewport } from 'next';
import { getLocale } from 'next-intl/server';
import { Inter, Playfair_Display } from 'next/font/google';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { PWAProvider } from '@/components/providers/pwa-provider';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Analytics } from '@vercel/analytics/next';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
});

const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://paraysco.com';

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default: 'Paraysco Consulting | Professional Solutions, Sustainable Growth',
    template: '%s',
  },
  description:
    'Paraysco Consulting provides innovative consultancy solutions that bridge the gap between ideas and implementation, investment and opportunity, and ambition and sustainable growth. Expert services in real estate, engineering, construction, and business consultancy across Africa.',
  authors: [{ name: 'Paraysco Consulting', url: baseUrl }],
  creator: 'Paraysco Consulting',
  publisher: 'Paraysco Consulting',
  category: 'Business Consulting',
  classification: 'Professional Services',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    alternateLocale: ['fr_FR'],
    url: baseUrl,
    siteName: 'Paraysco Consulting',
    title: 'Paraysco Consulting | Professional Solutions, Sustainable Growth',
    description:
      'Expert multidisciplinary consulting firm providing integrated solutions in real estate, engineering, construction, and business consultancy across Africa.',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Paraysco Consulting - Professional Solutions for Sustainable Growth',
      },
      {
        url: '/og-image-square.jpg',
        width: 1200,
        height: 1200,
        alt: 'Paraysco Consulting Logo',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Paraysco Consulting | Professional Solutions, Sustainable Growth',
    description:
      'Expert multidisciplinary consulting firm providing integrated solutions across Africa. Real estate, engineering, construction, and business consultancy.',
    images: ['/og-image.jpg'],
    creator: '@parayscoconsultin',
    site: '@parayscoconsultin',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: baseUrl,
    languages: {
      en: `${baseUrl}/en`,
      fr: `${baseUrl}/fr`,
    },
  },
  manifest: '/manifest.webmanifest',
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-16.png', sizes: '16x16', type: 'image/png' },
      { url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
  appleWebApp: {
    capable: true,
    title: 'Paraysco Consulting',
    statusBarStyle: 'default',
  },
};

export const viewport: Viewport = {
  themeColor: '#0d9488',
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let locale = 'en';
  try {
    locale = await getLocale();
  } catch {
    // Requests outside the locale prefix (e.g. admin, API) have no request locale.
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        {/* PWA / icon / theme-color tags and OG/Twitter cards are generated by the
            Metadata API above. JSON-LD structured data remains here. */}

        {/* LocalBusiness Schema - Critical for local SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'LocalBusiness',
              '@id': `${baseUrl}/#business`,
              name: 'Paraysco Consulting',
              description: 'Multidisciplinary professional consulting firm providing integrated solutions in real estate, engineering, construction, procurement, investment advisory, and business consultancy across Africa.',
              url: baseUrl,
              logo: `${baseUrl}/logo.png`,
              image: `${baseUrl}/og-image.jpg`,
              telephone: '+237-676-914-581',
              email: 'parayscoconsulting@gmail.com',
              address: {
                '@type': 'PostalAddress',
                streetAddress: 'Bota Middle Farms',
                addressLocality: 'Limbe',
                addressRegion: 'South West Region',
                postalCode: 'SWR',
                addressCountry: 'CM',
              },
              geo: {
                '@type': 'GeoCoordinates',
                latitude: '4.0167',
                longitude: '9.2000',
              },
              openingHoursSpecification: [
                {
                  '@type': 'OpeningHoursSpecification',
                  dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                  opens: '08:00',
                  closes: '17:00',
                },
              ],
              priceRange: '$$',
              areaServed: [
                { '@type': 'Country', name: 'Cameroon' },
                { '@type': 'Country', name: 'Nigeria' },
                { '@type': 'Country', name: 'Ghana' },
                { '@type': 'Country', name: 'Africa' },
              ],
              hasOfferCatalog: {
                '@type': 'OfferCatalog',
                name: 'Consulting Services',
                itemListElement: [
                  { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Real Estate Advisory' } },
                  { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Engineering Services' } },
                  { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Construction Management' } },
                  { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Procurement Services' } },
                  { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Investment Advisory' } },
                  { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Business Consultancy' } },
                ],
              },
              sameAs: [
                'https://www.facebook.com/share/1B3A4oumdE/',
                'https://www.instagram.com/parayscoconsultinginc',
                'https://www.tiktok.com/@parayscoconsultin',
                'https://www.linkedin.com/in/mola-scott-607760250',
              ],
            }),
          }}
        />

        {/* Organization Schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'Organization',
              '@id': `${baseUrl}/#organization`,
              name: 'Paraysco Consulting',
              alternateName: ['Paraysco Consulting Inc.', 'Paraysco', 'PCI'],
              description: 'Multidisciplinary professional consulting firm providing integrated solutions across real estate, engineering, construction, and business consultancy in Africa.',
              url: baseUrl,
              logo: `${baseUrl}/logo.png`,
              foundingDate: '2020',
              foundingLocation: 'Limbe, Cameroon',
              contactPoint: {
                '@type': 'ContactPoint',
                telephone: '+237-676-914-581',
                email: 'parayscoconsulting@gmail.com',
                contactType: 'customer service',
                availableLanguage: ['English', 'French'],
              },
              address: {
                '@type': 'PostalAddress',
                streetAddress: 'Bota Middle Farms',
                addressLocality: 'Limbe',
                addressRegion: 'South West Region',
                addressCountry: 'CM',
              },
              sameAs: [
                'https://www.facebook.com/share/1B3A4oumdE/',
                'https://www.instagram.com/parayscoconsultinginc',
                'https://www.tiktok.com/@parayscoconsultin',
                'https://www.linkedin.com/in/mola-scott-607760250',
              ],
              knowsAbout: [
                'Real Estate',
                'Engineering',
                'Construction Management',
                'Procurement',
                'Investment Advisory',
                'Business Consultancy',
                'Project Management',
                'Sustainable Development',
              ],
              areaServed: {
                '@type': 'Place',
                name: 'Africa',
              },
            }),
          }}
        />

        {/* WebSite Schema - Google can still use this for site names in results. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'WebSite',
              '@id': `${baseUrl}/#website`,
              name: 'Paraysco Consulting',
              url: baseUrl,
              description: 'Professional consulting services in real estate, engineering, construction, and business consultancy across Africa.',
              publisher: { '@id': `${baseUrl}/#organization` },
            }),
          }}
        />
      </head>
      <body className={`${inter.variable} ${playfair.variable} font-sans antialiased`}>
        <PWAProvider>
          <ThemeProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </ThemeProvider>
        </PWAProvider>
        <Analytics />
      </body>
    </html>
  );
}
